       
#include <apiset.h>
#include <apisetcconv.h>
#include <nt.h>
#include <ntrtl.h>
#include <nturtl.h>
#include <windows.h>
typedef enum GAMING_DEVICE_VENDOR_ID
{
    GAMING_DEVICE_VENDOR_ID_NONE = 0,
    GAMING_DEVICE_VENDOR_ID_MICROSOFT = 0xC2EC5032
} GAMING_DEVICE_VENDOR_ID;
typedef enum GAMING_DEVICE_DEVICE_ID
{
    GAMING_DEVICE_DEVICE_ID_NONE = 0,
    GAMING_DEVICE_DEVICE_ID_XBOX_ONE = 0x768BAE26,
    GAMING_DEVICE_DEVICE_ID_XBOX_ONE_S = 0x2A7361D9,
    GAMING_DEVICE_DEVICE_ID_XBOX_ONE_X = 0x5AD617C7,
    GAMING_DEVICE_DEVICE_ID_XBOX_ONE_X_DEVKIT = 0x10F7CDE3
} GAMING_DEVICE_DEVICE_ID;
typedef struct GAMING_DEVICE_MODEL_INFORMATION
{
    GAMING_DEVICE_VENDOR_ID vendorId;
    GAMING_DEVICE_DEVICE_ID deviceId;
} GAMING_DEVICE_MODEL_INFORMATION;
STDAPI
GetGamingDeviceModelInformation(
    _Out_ GAMING_DEVICE_MODEL_INFORMATION* information
    );
