#include <winapifamily.h>
#pragma region Desktop Family
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
                                            typedef enum tagIMMPID_##name##_ENUM {\
                                                IMMPID_##name##_BEFORE__ = (start)-1,
                                            } IMMPID_##name##_ENUM;
IMMPID_START_LIST(MP,0x1000,"13384CF0-B3C4-11d1-AA92-00AA006BC80B")
    IMMPID_MP_RECIPIENT_LIST,
    IMMPID_MP_CONTENT_FILE_NAME,
    IMMPID_MP_SENDER_ADDRESS_SMTP,
    IMMPID_MP_SENDER_ADDRESS_X500,
    IMMPID_MP_SENDER_ADDRESS_X400,
    IMMPID_MP_SENDER_ADDRESS_LEGACY_EX_DN,
    IMMPID_MP_DOMAIN_LIST,
    IMMPID_MP_PICKUP_FILE_NAME,
    IMMPID_MP_AUTHENTICATED_USER_NAME,
    IMMPID_MP_CONNECTION_IP_ADDRESS,
    IMMPID_MP_HELO_DOMAIN,
    IMMPID_MP_EIGHTBIT_MIME_OPTION,
    IMMPID_MP_CHUNKING_OPTION,
    IMMPID_MP_BINARYMIME_OPTION,
    IMMPID_MP_REMOTE_AUTHENTICATION_TYPE,
    IMMPID_MP_ERROR_CODE,
    IMMPID_MP_DSN_ENVID_VALUE,
    IMMPID_MP_DSN_RET_VALUE,
    IMMPID_MP_REMOTE_SERVER_DSN_CAPABLE,
    IMMPID_MP_ARRIVAL_TIME,
    IMMPID_MP_MESSAGE_STATUS,
    IMMPID_MP_EXPIRE_DELAY,
    IMMPID_MP_EXPIRE_NDR,
    IMMPID_MP_LOCAL_EXPIRE_DELAY,
    IMMPID_MP_LOCAL_EXPIRE_NDR,
    IMMPID_MP_ARRIVAL_FILETIME,
    IMMPID_MP_HR_CAT_STATUS,
    IMMPID_MP_MSG_GUID,
    IMMPID_MP_SUPERSEDES_MSG_GUID,
    IMMPID_MP_SCANNED_FOR_CRLF_DOT_CRLF,
    IMMPID_MP_FOUND_EMBEDDED_CRLF_DOT_CRLF,
    IMMPID_MP_MSG_SIZE_HINT,
    IMMPID_MP_RFC822_MSG_ID,
    IMMPID_MP_RFC822_MSG_SUBJECT,
    IMMPID_MP_RFC822_FROM_ADDRESS,
    IMMPID_MP_RFC822_TO_ADDRESS,
    IMMPID_MP_RFC822_CC_ADDRESS,
    IMMPID_MP_RFC822_BCC_ADDRESS,
    IMMPID_MP_CONNECTION_SERVER_IP_ADDRESS,
    IMMPID_MP_SERVER_NAME,
    IMMPID_MP_SERVER_VERSION,
    IMMPID_MP_NUM_RECIPIENTS,
    IMMPID_MP_X_PRIORITY,
    IMMPID_MP_FROM_ADDRESS,
    IMMPID_MP_SENDER_ADDRESS,
    IMMPID_MP_DEFERRED_DELIVERY_FILETIME,
    IMMPID_MP_SENDER_ADDRESS_OTHER,
    IMMPID_MP_ORIGINAL_ARRIVAL_TIME,
    IMMPID_MP_MSGCLASS,
    IMMPID_MP_CONTENT_TYPE,
    IMMPID_MP_ENCRYPTION_TYPE,
    IMMPID_MP_CONNECTION_SERVER_PORT,
    IMMPID_MP_CLIENT_AUTH_USER,
    IMMPID_MP_CLIENT_AUTH_TYPE,
    IMMPID_MP_CRC_GLOBAL,
    IMMPID_MP_CRC_RECIPS,
    IMMPID_MP_INBOUND_MAIL_FROM_AUTH,
IMMPID_END_LIST(MP)
IMMPID_START_LIST(RP,0x2000,"79E82048-D320-11d1-9FF4-00C04FA37348")
    IMMPID_RP_DSN_NOTIFY_SUCCESS,
    IMMPID_RP_DSN_NOTIFY_INVALID,
    IMMPID_RP_ADDRESS_TYPE,
    IMMPID_RP_ADDRESS,
    IMMPID_RP_ADDRESS_TYPE_SMTP,
    IMMPID_RP_ERROR_CODE,
    IMMPID_RP_ERROR_STRING,
    IMMPID_RP_DSN_NOTIFY_VALUE,
    IMMPID_RP_DSN_ORCPT_VALUE,
    IMMPID_RP_ADDRESS_SMTP,
    IMMPID_RP_ADDRESS_X400,
    IMMPID_RP_ADDRESS_X500,
    IMMPID_RP_LEGACY_EX_DN,
    IMMPID_RP_RECIPIENT_FLAGS,
    IMMPID_RP_SMTP_STATUS_STRING,
    IMMPID_RP_DSN_PRE_CAT_ADDRESS,
    IMMPID_RP_MDB_GUID,
    IMMPID_RP_USER_GUID,
    IMMPID_RP_DOMAIN,
    IMMPID_RP_ADDRESS_OTHER,
    IMMPID_RP_DISPLAY_NAME,
IMMPID_END_LIST(RP)
IMMPID_START_LIST(MPV,0x3000,"CBE69706-C9BD-11d1-9FF2-00C04FA37348")
    IMMPID_MPV_STORE_DRIVER_HANDLE,
    IMMPID_MPV_MESSAGE_CREATION_FLAGS,
    IMMPID_MPV_MESSAGE_OPEN_HANDLES,
    IMMPID_MPV_TOTAL_OPEN_HANDLES,
    IMMPID_MPV_TOTAL_OPEN_PROPERTY_STREAM_HANDLES,
    IMMPID_MPV_TOTAL_OPEN_CONTENT_HANDLES,
IMMPID_END_LIST(MPV)
typedef struct tagIMMP_MPV_STORE_DRIVER_HANDLE {
    GUID guidSignature;
} IMMP_MPV_STORE_DRIVER_HANDLE;
IMMPID_START_LIST(RPV,0x4000,"79E82049-D320-11d1-9FF4-00C04FA37348")
    IMMPID_RPV_DONT_DELIVER,
    IMMPID_RPV_NO_NAME_COLLISIONS,
IMMPID_END_LIST(RPV)
IMMPID_START_LIST(NMP,0x6000,"7433a9aa-20e2-11d2-94d6-00c04fa379f1")
    IMMPID_NMP_SECONDARY_GROUPS,
    IMMPID_NMP_SECONDARY_ARTNUM,
    IMMPID_NMP_PRIMARY_GROUP,
    IMMPID_NMP_PRIMARY_ARTID,
    IMMPID_NMP_POST_TOKEN,
    IMMPID_NMP_NEWSGROUP_LIST,
    IMMPID_NMP_HEADERS,
    IMMPID_NMP_NNTP_PROCESSING,
    IMMPID_NMP_NNTP_APPROVED_HEADER,
IMMPID_END_LIST(NMP)
IMMPID_START_LIST(CPV,0x8000,"A2A76B2A-E52D-11d1-AA64-00C04FA35B82")
    IMMPID_CP_START,
IMMPID_END_LIST(CPV)
                                     IMMPID_##name##_BEFORE__+1,\
                                     IMMPID_##name##_AFTER__-1}
extern const __declspec(selectany) struct tagIMMPID_GUIDLIST_ITEM {
                                       const GUID *pguid;
                                       DWORD dwStart;
                                       DWORD dwLast;
                                   } IMMPID_GUIDS[] = {IMMPID_DECLARE_ENTRY(MP),
                                                       IMMPID_DECLARE_ENTRY(RP),
                                                       IMMPID_DECLARE_ENTRY(MPV),
                                                       IMMPID_DECLARE_ENTRY(RPV),
                                                       {&GUID_NULL,0,0}};
#endif
#pragma endregion
