    #define WDF_EXTERN_C extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END }
WDF_EXTERN_C_START
DECLARE_HANDLE( NETADAPTER );
DECLARE_HANDLE( NETCONFIGURATION );
DECLARE_HANDLE( NETREQUEST );
DECLARE_HANDLE( NETREQUESTQUEUE );
DECLARE_HANDLE( NETOFFLOAD );
DECLARE_HANDLE( NETPACKETQUEUE );
DECLARE_HANDLE( NETPOWERSETTINGS );
struct _NETADAPTER_INIT;
typedef struct _NETADAPTER_INIT NETADAPTER_INIT;
typedef struct _NET_DRIVER_GLOBALS {
    ULONG Unused;
} NET_DRIVER_GLOBALS, *PNET_DRIVER_GLOBALS;
typedef void (*NETFUNC) (void);
extern NETFUNC NetFunctions[];
WDF_EXTERN_C_END
