#include "nodetype.h"
typedef PVOID RX_HANDLE, *PRX_HANDLE;
typedef KSPIN_LOCK RX_SPIN_LOCK;
typedef PKSPIN_LOCK PRX_SPIN_LOCK;
typedef struct _BINDING_HANDLE {
    RX_HANDLE pTdiEmulationContext;
    RX_HANDLE pTransportInformation;
} RX_BINDING_HANDLE, *PRX_BINDING_HANDLE;
typedef UNICODE_STRING UNICODE_STRING;
typedef UNICODE_STRING* PUNICODE_STRING;
typedef struct _RX_BINDING_CONTEXT {
    PUNICODE_STRING pTransportName;
    ULONG QualityOfService;
    PRX_BINDING_HANDLE pBindHandle;
    } RX_BINDING_CONTEXT, *PRX_BINDING_CONTEXT;
