       
typedef struct _SIDEBANDAUDIO_DEVICE_DESCRIPTOR
{
    ULONG NumberOfEndpoints;
}SIDEBANDAUDIO_DEVICE_DESCRIPTOR, *PSIDEBANDAUDIO_DEVICE_DESCRIPTOR;
typedef struct _SIDEBANDAUDIO_ENDPOINT_CAPABILITIES
{
    BOOL Volume;
    BOOL Mute;
    BOOL Sidetone;
    BOOL Feedback;
}SIDEBANDAUDIO_ENDPOINT_CAPABILITIES;
typedef struct _SIDEBANDAUDIO_ENDPOINT_DESCRIPTOR
{
    ULONG CbSize;
    GUID ContainerId;
    GUID Category;
    KSPIN_DATAFLOW Direction;
    SIDEBANDAUDIO_ENDPOINT_CAPABILITIES Capabilities;
    UNICODE_STRING FriendlyName;
    ULONG VolumePropertyValuesSize;
    ULONG SidetoneVolumePropertyValueSize;
}SIDEBANDAUDIO_ENDPOINT_DESCRIPTOR, *PSIDEBANDAUDIO_ENDPOINT_DESCRIPTOR;
typedef struct _SIDEBANDAUDIO_VOLUME_PARAMS
{
    ULONG EpIndex;
    BOOL Immediate;
    LONG Channel;
    LONG Value;
}SIDEBANDAUDIO_VOLUME_PARAMS, *PSIDEBANDAUDIO_VOLUME_PARAMS;
typedef struct _SIDEBANDAUDIO_MUTE_PARAMS
{
    ULONG EpIndex;
    BOOL Immediate;
    LONG Channel;
    BOOL Value;
}SIDEBANDAUDIO_MUTE_PARAMS, *PSIDEBANDAUDIO_MUTE_PARAMS;
typedef struct _SIDEBANDAUDIO_STREAM_STATUS_PARAMS
{
    ULONG EpIndex;
    BOOL Immediate;
    NTSTATUS Status;
}SIDEBANDAUDIO_STREAM_STATUS_PARAMS, *PSIDEBANDAUDIO_STREAM_STATUS_PARAMS;
typedef struct _SIDEBANDAUDIO_CONNECTION_PARAMS
{
    ULONG EpIndex;
    BOOL Immediate;
    BOOL Connected;
}SIDEBANDAUDIO_CONNECTION_PARAMS, *PSIDEBANDAUDIO_CONNECTION_PARAMS;
typedef struct _SIDEBANDAUDIO_SUPPORTED_FORMATS
{
    ULONG CbSize;
    ULONG EpIndex;
    ULONG NumFormats;
    PKSDATAFORMAT *Formats;
}SIDEBANDAUDIO_SUPPORTED_FORMATS, *PSIDEBANDAUDIO_SUPPORTED_FORMATS;
DEFINE_GUID(SIDEBANDAUDIO_PARAMS_SET_STANDARD,
    0xbf34616b, 0x8265, 0x4d70, 0xad, 0xb2, 0x91, 0xb3, 0x50, 0xcc, 0xd5, 0xd2);
typedef enum _SIDEBANDAUDIO_PARAMS_MSFT_TYPE_ID
{
    SBAUD_PARAMS_TYPE_RESERVED
}SIDEBANDAUDIO_PARAMS_MSFT_TYPE_ID;
typedef union
{
    struct
    {
        GUID ParamSet;
        ULONG TypeId;
        ULONG Size;
    };
    LONGLONG Alignment;
}SIDEBANDAUDIO_IO_PARAM_HEADER, *PSIDEBANDAUDIO_IO_PARAM_HEADER;
typedef union
{
    struct
    {
        ULONG EpIndex;
        SIDEBANDAUDIO_IO_PARAM_HEADER RequestedSiop;
    };
    LONGLONG Alignment;
}SIDEBANDAUDIO_SIOP_REQUEST_PARAM, *PSIDEBANDAUDIO_SIOP_REQUEST_PARAM;
typedef union
{
    struct
    {
        ULONG EpIndex;
        PKSDATAFORMAT Format;
        ULONG SiopCount;
    };
    LONGLONG Alignment;
}SIDEBANDAUDIO_STREAM_OPEN_PARAMS, *PSIDEBANDAUDIO_STREAM_OPEN_PARAMS;
typedef struct _SIDEBANDAUDIO_SIDETONE_DESCRIPTOR
{
    LONG Volume;
    BOOL Mute;
}SIDEBANDAUDIO_SIDETONE_DESCRIPTOR, *PSIDEBANDAUDIO_SIDETONE_DESCRIPTOR;
typedef struct _SIDEBANDAUDIO_SIDETONE_PARAMS
{
    ULONG EpIndex;
    BOOL Immediate;
    LONG Channel;
    SIDEBANDAUDIO_SIDETONE_DESCRIPTOR Sidetone;
}SIDEBANDAUDIO_SIDETONE_PARAMS, *PSIDEBANDAUDIO_SIDETONE_PARAMS;
typedef struct _SIDEBANDAUDIO_DEVICE_ERROR
{
    ULONG EpIndex;
    BOOL Immediate;
    NTSTATUS Status;
}SIDEBANDAUDIO_DEVICE_ERROR, *PSIDEBANDAUDIO_DEVICE_ERROR;
    CTL_CODE (FILE_DEVICE_UNKNOWN, _index_, METHOD_NEITHER, FILE_ANY_ACCESS)
