       
#include <sffdisk.h>
#include <ntddstor.h>
DEFINE_GUID(GUID_TREE_RPMB_SERVICE,
            0x5272f96, 0xad1a, 0x4497, 0x97, 0xc2, 0x16, 0xb9, 0x65, 0xb1, 0x97, 0xb3);
typedef struct _TREE_RPMB_AUTHENTICATED_WRITE_EX_INPUT {
    ULONG WriteFrameCount;
    ULONG ReliableWriteSizeOverride;
    SFFDISK_DEVICE_RPMB_DATA_FRAME Data[1];
} TREE_RPMB_AUTHENTICATED_WRITE_EX_INPUT, *PTREE_RPMB_AUTHENTICATED_WRITE_EX_INPUT;
typedef struct _TREE_RPMB_AUTHENTICATED_WRITE_EX_OUTPUT {
    ULONG ResponseFrameCount;
    ULONG FramesWritten;
    SFFDISK_DEVICE_RPMB_DATA_FRAME Data[1];
} TREE_RPMB_AUTHENTICATED_WRITE_EX_OUTPUT, *PTREE_RPMB_AUTHENTICATED_WRITE_EX_OUTPUT;
typedef struct _TREE_RPMB_COMMAND_INPUT {
    ULONG InputFrameCount;
    ULONG FramesPerTransaction;
    STORAGE_RPMB_DATA_FRAME Data[1];
} TREE_RPMB_COMMAND_INPUT, *PTREE_RPMB_COMMAND_INPUT;
typedef struct _TREE_RPMB_COMMAND_OUTPUT {
    ULONG OutputFrameCount;
    ULONG FramesWritten;
    STORAGE_RPMB_DATA_FRAME Data[1];
} TREE_RPMB_COMMAND_OUTPUT, *PTREE_RPMB_COMMAND_OUTPUT;
