    #define WDF_EXTERN_C extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END }
WDF_EXTERN_C_START
typedef struct _UCMUCSI_DRIVER_GLOBALS {
    ULONG Reserved;
} UCMUCSI_DRIVER_GLOBALS, *PUCMUCSI_DRIVER_GLOBALS;
WDF_EXTERN_C_END
