    #define WDF_EXTERN_C extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END }
WDF_EXTERN_C_START
typedef struct _UCX_DRIVER_GLOBALS {
    ULONG Size;
    PWDF_DRIVER_GLOBALS WdfDriverGlobals;
} UCX_DRIVER_GLOBALS, *PUCX_DRIVER_GLOBALS;
typedef UCX_DRIVER_GLOBALS UCX_GLOBALS;
typedef PUCX_DRIVER_GLOBALS PUCX_GLOBALS;
WDF_EXTERN_C_END
