    #define WDF_EXTERN_C extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END }
WDF_EXTERN_C_START
DECLARE_HANDLE(UDECXUSBDEVICE);
WDF_DECLARE_CUSTOM_TYPE(UDECXUSBDEVICE);
typedef struct _UDECXUSBDEVICE_INIT *PUDECXUSBDEVICE_INIT;
DECLARE_HANDLE(UDECXUSBENDPOINT);
WDF_DECLARE_CUSTOM_TYPE(UDECXUSBENDPOINT);
typedef struct _UDECXUSBENDPOINT_INIT *PUDECXUSBENDPOINT_INIT;
typedef struct _UDECX_DRIVER_GLOBALS {
    ULONG Unused;
} UDECX_DRIVER_GLOBALS, *PUDECX_DRIVER_GLOBALS;
typedef VOID (*UDECXFUNC) (VOID);
extern UDECXFUNC UdecxFunctions[];
WDF_EXTERN_C_END
