       
#include <poclass.h>
#include <charging.h>
typedef struct _UFX_PROPRIETARY_CHARGER {
    GUID ChargerId;
    DEVICE_POWER_STATE DxState;
} UFX_PROPRIETARY_CHARGER, *PUFX_PROPRIETARY_CHARGER;
typedef
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
UFX_PROPRIETARY_CHARGER_DETECT (
    _In_ PVOID Context,
    _Out_ PUFX_PROPRIETARY_CHARGER DetectedCharger
    );
typedef UFX_PROPRIETARY_CHARGER_DETECT *PFN_UFX_PROPRIETARY_CHARGER_DETECT;
typedef
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
UFX_PROPRIETARY_CHARGER_SET_PROPERTY (
    _In_ PVOID Context,
    _In_ PCONFIGURABLE_CHARGER_PROPERTY_HEADER Property
    );
typedef UFX_PROPRIETARY_CHARGER_SET_PROPERTY *PFN_UFX_PROPRIETARY_CHARGER_SET_PROPERTY;
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
NTSTATUS
UFX_PROPRIETARY_CHARGER_ABORT_OPERATION (
    _In_ PVOID Context
    );
typedef UFX_PROPRIETARY_CHARGER_ABORT_OPERATION *PFN_UFX_PROPRIETARY_CHARGER_ABORT_OPERATION;
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
NTSTATUS
UFX_PROPRIETARY_CHARGER_RESET_OPERATION (
    _In_ PVOID Context
    );
typedef UFX_PROPRIETARY_CHARGER_RESET_OPERATION *PFN_UFX_PROPRIETARY_CHARGER_RESET_OPERATION;
DEFINE_GUID(GUID_UFX_INTERFACE_PROPRIETARY_CHARGER,
0xd3d11a34, 0xaba6, 0x40d6, 0xb8, 0x1e, 0x99, 0xd0, 0xf6, 0x66, 0x2d, 0xf2);
typedef struct _UFX_INTERFACE_PROPRIETARY_CHARGER {
    INTERFACE InterfaceHeader;
    PFN_UFX_PROPRIETARY_CHARGER_DETECT ProprietaryChargerDetect;
    PFN_UFX_PROPRIETARY_CHARGER_SET_PROPERTY ProprietaryChargerSetProperty;
    PFN_UFX_PROPRIETARY_CHARGER_ABORT_OPERATION ProprietaryChargerAbortOperation;
    PFN_UFX_PROPRIETARY_CHARGER_RESET_OPERATION ProprietaryChargerResetOperation;
} UFX_INTERFACE_PROPRIETARY_CHARGER, *PUFX_INTERFACE_PROPRIETARY_CHARGER;
