       
DEFINE_GUID (GUID_DEVINTERFACE_USB_SIDEBAND_AUDIO_HS_HCIBYPASS,
    0x2baa4b5, 0x33b5, 0x4d97, 0xae, 0x4f, 0xe8, 0x6d, 0xde, 0x17, 0x53, 0x6f);
DEFINE_GUID(SIDEBANDAUDIO_PARAMS_SET_USBAUDIO,
    0x17e71b09, 0x4f0d, 0x4813, 0xb3, 0x30, 0x5c, 0x92, 0x47, 0xdf, 0xce, 0x17);
typedef enum _SIDEBANDAUDIO_EP_USB_TRANSPORT_RESOURCE_TYPE
{
    SIOP_TYPE_USBAUD_USBD_INTERFACE_DESCRIPTOR,
    SIOP_TYPE_USBAUD_EP_USBD_ENDPOINT_DESCRIPTOR,
    SIOP_TYPE_USBAUD_EP_USBD_ENDPOINT_OFFLOAD_INFORMATION,
    SIOP_TYPE_USBAUD_EP_USBAUDIO_TRANSPORT_RESOURCES,
    SIOP_TYPE_USBAUD_EP_OFFLOAD_RESOURCE_ID,
    SIOP_TYPE_USBAUD_FB_EP_USBD_ENDPOINT_DESCRIPTOR,
    SIOP_TYPE_USBAUD_FB_EP_USBD_ENDPOINT_OFFLOAD_INFORMATION,
    SIOP_TYPE_USBAUD_FB_EP_USBAUDIO_TRANSPORT_RESOURCES,
    SIOP_TYPE_USBAUD_FB_EP_OFFLOAD_RESOURCE_ID,
    SIOP_TYPE_USBAUD_ENDPOINT_DESCRIPTOR_PER_FORMAT,
    SBUSBAUD_EP_TRANSPORT_RESOURCE_TYPE_INVALID,
}SIDEBANDAUDIO_EP_USB_TRANSPORT_RESOURCE_TYPE;
typedef struct _SIDEBANDAUDIO_EP_USBAUDIO_TRANSPORT_RESOURCES
{
    USHORT bcdAudioSpec;
    UCHAR bDelay;
    UCHAR bSlotSize;
}SIDEBANDAUDIO_EP_USBAUDIO_TRANSPORT_RESOURCES, *PSIDEBANDAUDIO_EP_USBAUDIO_TRANSPORT_RESOURCES;
